# Generated by Django 6.0.3 on 2026-04-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilrecord',
            old_name='nitrogen',
            new_name='soil_temperature',
        ),
        migrations.RemoveField(
            model_name='soilrecord',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='soilrecord',
            name='potassium',
        ),
    ]
