# Generated by Django 6.0.3 on 2026-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_api', '0002_rename_nitrogen_soilrecord_soil_temperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilrecord',
            old_name='moisture',
            new_name='soil_moisture',
        ),
    ]
