# Generated by Django 6.0.3 on 2026-04-06 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil_api', '0003_rename_moisture_soilrecord_soil_moisture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilrecord',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='soilrecord',
            name='farmer',
        ),
        migrations.AddField(
            model_name='soilrecord',
            name='battery_percentage',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='soilrecord',
            name='plot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='soil_api.farmplot'),
            preserve_default=False,
        ),
    ]
